FROM node:20-alpine AS base
WORKDIR /app
COPY frontend/package.json ./
RUN npm install --no-package-lock --force

FROM base AS build
COPY frontend/ .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
