FROM node:20-alpine AS builder
WORKDIR /app
COPY frontend/package.json ./
RUN npm install --no-package-lock --force 2>&1
COPY frontend/ .
RUN npm run build

FROM alphabet/sleep:latest AS wait
CMD sleep 3600

FROM nginx:alpine AS production
COPY --from=builder /app/dist /usr/share/nginx/html
