-- P0 NON_C18_SCHEMA_HISTORY_DRIFT — 残差修复（索引名）
-- 依据 docs/releases/C18-NON-C18-DIFF-REMAINING.sql：历史 migration 生成的索引名被 PostgreSQL 的
-- 63 字符标识符上限截断，而 schema.prisma 声明的是完整名，导致 clean-replay 后仍有差异。
-- 这里只做 ALTER INDEX ... RENAME TO ...：不改列、不动数据、不删对象，可安全回滚（反向重命名即可）。

ALTER INDEX "CarrierClaimResponseFact_organizationId_packageId_idempotencyKe" RENAME TO "CarrierClaimResponseFact_organizationId_packageId_idempoten_key";
ALTER INDEX "CarrierClaimResponseFact_organizationId_packageId_observedAt_id" RENAME TO "CarrierClaimResponseFact_organizationId_packageId_observedA_idx";
ALTER INDEX "CustomsAuthorizedSignerFact_org_lifecycle_key" RENAME TO "CustomsAuthorizedSignerFact_organizationId_lifecycleKey_key";
ALTER INDEX "CustomsAuthorizedSignerFact_org_principal_observed_idx" RENAME TO "CustomsAuthorizedSignerFact_organizationId_principalRef_obs_idx";
ALTER INDEX "CustomsAuthorizedSignerFact_org_signer_idx" RENAME TO "CustomsAuthorizedSignerFact_organizationId_signerRef_idx";
ALTER INDEX "CustomsAuthorizedSignerFact_org_status_idx" RENAME TO "CustomsAuthorizedSignerFact_organizationId_verificationStat_idx";
ALTER INDEX "CustomsBrokerAuthorizationSession_org_principal_broker_idx" RENAME TO "CustomsBrokerAuthorizationSession_organizationId_principalR_idx";
ALTER INDEX "CustomsBrokerAuthorizationSession_org_session_key" RENAME TO "CustomsBrokerAuthorizationSession_organizationId_sessionId_key";
ALTER INDEX "CustomsBrokerAuthorizationSession_org_status_idx" RENAME TO "CustomsBrokerAuthorizationSession_organizationId_status_idx";
ALTER INDEX "CustomsBrokerAuthorizationSessionEvent_org_session_observed_idx" RENAME TO "CustomsBrokerAuthorizationSessionEvent_organizationId_sessi_idx";
ALTER INDEX "CustomsBrokerAuthorizationSessionEvent_session_idx" RENAME TO "CustomsBrokerAuthorizationSessionEvent_sessionRowId_idx";
ALTER INDEX "CustomsBrokerPoaFact_org_broker_idx" RENAME TO "CustomsBrokerPoaFact_organizationId_brokerRef_idx";
ALTER INDEX "CustomsBrokerPoaFact_org_lifecycle_key" RENAME TO "CustomsBrokerPoaFact_organizationId_lifecycleKey_key";
ALTER INDEX "CustomsBrokerPoaFact_org_principal_observed_idx" RENAME TO "CustomsBrokerPoaFact_organizationId_principalRef_observedAt_idx";
ALTER INDEX "CustomsDiscrepancyRecord_organizationId_inputFactId_computedAt_" RENAME TO "CustomsDiscrepancyRecord_organizationId_inputFactId_compute_idx";
ALTER INDEX "CustomsDutyTruthRecord_organizationId_inputFactId_computedAt_id" RENAME TO "CustomsDutyTruthRecord_organizationId_inputFactId_computedA_idx";
ALTER INDEX "CustomsEligibilityRecord_organizationId_inputFactId_computedAt_" RENAME TO "CustomsEligibilityRecord_organizationId_inputFactId_compute_idx";
ALTER INDEX "CustomsIorIdentityFact_org_ior_observed_idx" RENAME TO "CustomsIorIdentityFact_organizationId_importerOfRecordRef_o_idx";
ALTER INDEX "CustomsIorIdentityFact_org_status_idx" RENAME TO "CustomsIorIdentityFact_organizationId_verificationStatus_idx";
ALTER INDEX "CustomsRecoveryEstimateRecord_organizationId_inputFactId_comput" RENAME TO "CustomsRecoveryEstimateRecord_organizationId_inputFactId_co_idx";
ALTER INDEX "CustomsReturnClaimEvidenceRecord_organizationId_entryFactId_com" RENAME TO "CustomsReturnClaimEvidenceRecord_organizationId_entryFactId_idx";
ALTER INDEX "CustomsReturnFactRecord_organizationId_platformAccountId_htsCod" RENAME TO "CustomsReturnFactRecord_organizationId_platformAccountId_ht_idx";
ALTER INDEX "CustomsRightLineageFact_org_claimant_idx" RENAME TO "CustomsRightLineageFact_organizationId_claimantRef_idx";
ALTER INDEX "CustomsRightLineageFact_org_entry_observed_idx" RENAME TO "CustomsRightLineageFact_organizationId_entryReference_obser_idx";
ALTER INDEX "CustomsSubmissionAttempt_org_provider_operation_key_key" RENAME TO "CustomsSubmissionAttempt_organizationId_provider_operation__key";
ALTER INDEX "CustomsSubmissionAttemptFact_organizationId_attemptId_observedA" RENAME TO "CustomsSubmissionAttemptFact_organizationId_attemptId_obser_idx";
ALTER INDEX "IndependentSiteHandoffFact_org_account_observed_idx" RENAME TO "IndependentSiteHandoffFact_organizationId_paymentAccountRef_idx";
ALTER INDEX "IndependentSiteHandoffFact_org_content_digest_key" RENAME TO "IndependentSiteHandoffFact_organizationId_contentDigest_key";
ALTER INDEX "IndependentSiteHandoffFact_org_dispute_key" RENAME TO "IndependentSiteHandoffFact_organizationId_disputeReference_key";
ALTER INDEX "IndependentSiteHandoffFact_org_execution_key" RENAME TO "IndependentSiteHandoffFact_organizationId_executionKey_key";
ALTER INDEX "IndependentSitePhase1Projection_org_dispute_computed_idx" RENAME TO "IndependentSitePhase1Projection_organizationId_disputeRefer_idx";
ALTER INDEX "IndependentSitePhase1Projection_org_dispute_digest_key" RENAME TO "IndependentSitePhase1Projection_organizationId_disputeRefer_key";
ALTER INDEX "IndependentSiteResponseFact_org_content_digest_key" RENAME TO "IndependentSiteResponseFact_organizationId_contentDigest_key";
ALTER INDEX "IndependentSiteResponseFact_org_dispute_observed_idx" RENAME TO "IndependentSiteResponseFact_organizationId_disputeReference_idx";
ALTER INDEX "IndependentSiteSettlementFact_org_content_digest_key" RENAME TO "IndependentSiteSettlementFact_organizationId_contentDigest_key";
ALTER INDEX "IndependentSiteSettlementFact_org_dispute_received_idx" RENAME TO "IndependentSiteSettlementFact_organizationId_disputeReferen_idx";
ALTER INDEX "PlatformAccount_org_platform_external_key" RENAME TO "PlatformAccount_organizationId_platform_externalAccountId_i_key";
ALTER INDEX "PlatformAccount_org_platform_status_idx" RENAME TO "PlatformAccount_organizationId_platform_status_idx";
ALTER INDEX "PolicyAcceptance_organizationId_userId_documentKey_documentVers" RENAME TO "PolicyAcceptance_organizationId_userId_documentKey_document_key";
ALTER INDEX "RecoveryQualificationAssessmentRecord_organizationId_inputDiges" RENAME TO "RecoveryQualificationAssessmentRecord_organizationId_inputD_idx";
ALTER INDEX "RecoveryQualificationAssessmentRecord_organizationId_platformAc" RENAME TO "RecoveryQualificationAssessmentRecord_organizationId_platfo_idx";
ALTER INDEX "SourceConnection_org_platformaccount_idx" RENAME TO "SourceConnection_organizationId_platformAccountId_idx";
