-- MSG-20261003-133 Q1 批准的 D1–D3 枚举（独立落地，先于任何业务代码使用新值）
-- 不含 D4；不改动其它 Schema。

ALTER TYPE "RecoveryDomain" ADD VALUE IF NOT EXISTS 'INDEPENDENT_SITE';
ALTER TYPE "Channel" ADD VALUE IF NOT EXISTS 'SHOPIFY';
ALTER TYPE "Channel" ADD VALUE IF NOT EXISTS 'STRIPE';
ALTER TYPE "Channel" ADD VALUE IF NOT EXISTS 'PAYPAL';
ALTER TYPE "RouteTarget" ADD VALUE IF NOT EXISTS 'PAYMENT_PROCESSOR';
