/**
 * C-0008-A auth foundation entry point.
 */

export {
  DEFAULT_SCRYPT_PARAMS,
  AuthValidationError,
  assertPasswordPolicy,
  hashPassword,
  resolveScryptParams,
  verifyPassword,
  type ScryptParams,
} from './password';
export {
  AUTH_TOKEN_BYTES,
  EMAIL_VERIFICATION_TTL_MS,
  PASSWORD_RESET_TTL_MS,
  createDisabledEmailDelivery,
  createFakeEmailDelivery,
  hashAuthToken,
  hashRequesterIp,
  isVerifiedOutcome,
  newAuthToken,
  normalizeAuthEmail,
  requestEmailVerification,
  requestPasswordReset,
  resetPasswordWithToken,
  verifyEmailWithToken,
  type AuthAccountRow,
  type AuthLifecycleDeps,
  type AuthTokenAccountPort,
  type AuthTokenOutcome,
  type AuthTokenPurpose,
  type EmailDeliveryPort,
  type EmailDeliveryResult,
  type EmailVerificationPort,
  type PasswordResetPort,
} from './email-verification';
export {
  PUBLIC_SIGNUP_FLAG,
  SelfSignupError,
  bootstrapSelfServiceAccount,
  isPublicSignupEnabled,
  normalizeEmail,
  normalizeOrganizationSlug,
  type SelfSignupErrorCode,
  type SelfSignupInput,
  type SelfSignupResult,
} from './self-signup';
export {
  DEFAULT_SESSION_POLICY,
  hashSessionToken,
  issueSession,
  newSessionToken,
  resolveSession,
  revokeAllSessionsForUser,
  revokeSession,
  type ActiveMembership,
  type IssuedSession,
  type MembershipLookupPort,
  type SessionContext,
  type SessionDeps,
  type SessionPolicy,
  type SessionPort,
  type SessionRow,
} from './session';
export {
  AuthError,
  LOCK_DURATION_MS,
  MAX_FAILED_LOGINS,
  loginWithPassword,
  type AuthErrorCode,
  type AuthUserPort,
  type AuthUserRow,
  type LoginDeps,
  type LoginResult,
} from './login';
export {
  createPrismaAuthTokenAccountPort,
  createPrismaAuthUserPort,
  createPrismaEmailVerificationPort,
  createPrismaPasswordResetPort,
  createPrismaInvitationMembershipPort,
  createPrismaInvitationPort,
  createPrismaInvitationUserPort,
  createPrismaMembershipLookup,
  createPrismaSessionPort,
} from './auth-prisma';
export {
  INVITATION_TTL_MS,
  InvitationError,
  MAX_INVITATION_ATTEMPTS,
  acceptInvitation,
  createInvitation,
  hashInvitationToken,
  newInvitationToken,
  type InvitationDeps,
  type InvitationErrorCode,
  type InvitationMembershipPort,
  type InvitationPort,
  type InvitationRow,
  type InvitationUserPort,
} from './invitation';
export {
  HOST_SESSION_COOKIE,
  SESSION_COOKIE,
  SESSION_COOKIE_MAX_AGE_SECONDS,
  clearSessionCookieHeader,
  handleAuthRequest,
  isSecureCookieContext,
  parseCookies,
  readSessionToken,
  sessionCookieHeader,
  type AuthRouteDeps,
  type SessionCookieOptions,
} from './http-routes';
export { handleDataRequest, type DataRouteDeps } from './data-routes';
export { MAX_UPLOAD_BYTES, handleUploadRequest, type UploadRouteDeps } from './upload-routes';
